name: MiniGameWorld-Reward
main: com.worldbiomusic.minigameworldreward.MiniGameWorldRewardMain
version: 1.6
author: worldbiomusic
description: minigame reward plugin of MiniGameWorld 
api-version: 1.14
depend: [MiniGameWorld]
softdepend: [MiniGameWorld-Rank]

commands:
  reward:
    aliases: [re]